name: pomchat
services:
- name: web
  dockerfile_path: Dockerfile
  source_dir: /
  github:
    branch: main
    deploy_on_push: true
    repo: InquilineKea/pomchat
  health_check:
    http_path: /
  http_port: 8000
  instance_count: 1
  instance_size_slug: basic-xs
